name: minesweeper
description: "minesweeper game"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  logger: ^2.4.0
  segment_display: ^0.5.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter_launcher_icons:
  android: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  windows:
    generate: true
    image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: mine-sweeper
      fonts:
        - asset: assets/fonts/mine-sweeper.ttf
